package com.medilog.medilog.models;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Date;

@Data
@Document(collection = "patients")
public class Patient {
    @Id
    private String id; // Auto-generated by MongoDB
    private String name;
    private Date dateOfBirth;
    private String gender;
    private Date createdAt = new Date(); // Auto-filled
    private String username;        
    private String password;

    
}

